### ISSUE TITLE
움짤과 동영상도 게시글에 올라갈 수 있도록 합니다

### ISSUE THREAD

**Issue by keinn51** [Together42/frontend#49]
mov와 mp4확장자도 올라갈 수 있습니다.

## 구현해야할 사항

- [x] 동영상 미리보기
- [x] 이미지는 img로, 동영상은 video 태그로 렌더링하기

**Comment by kth2624** [comment]
gif는 그냥 올라갑니다! 
mp4와 mov확장자 해주십쇼!

**Comment by keinn51** [comment]
74e7884bef4a2310bf8f78ac19f711683206afdc
