### ISSUE TITLE
BUG: 이전에 선택한 카테고리가 유지되는 상황에서 UI에는 올바르게 반영되지 못하는 상황

### ISSUE THREAD

**Issue by jhj9109** [Together42/frontend#87]
# 버그 발생 내용

검색시 카테고리탭이 유지가 되는데
이때 새로운 검색 결과에 해당 카테고리에는 결과값이 존재하지 않을때, 기대와 다른 UI가 출력되는 상황

# 버그 재현
1. 카테고리를 하나 선택한다. (여기서는 IT 일반)
<img width="706" alt="image" src="https://user-images.githubusercontent.com/36416495/210740722-80ba221a-fdbe-41fe-8485-7869689e96b3.png">

2. 새로운 검색어로 검색 결과를 갱신한다. 이때 카테고리가 유지되는 것을 확인할 수 있다. 검색 결과에 해당 카테고리의 책도 포함될 경우, 의도에 따라 정상적인 UI상황으로 볼 수 있다.
<img width="723" alt="image" src="https://user-images.githubusercontent.com/36416495/210740883-20d23bf2-cf52-407d-9588-be757a3eca81.png">

3. 다시한번 새로운 검색어로 검색 결과를 갱신한다. 이때 카테고리가 유지되는 것으로 보인다. 그리고 검색 결과에 해당 카테고리의 책이 포함되지 않을 경우, 기대와 다른 UI가 출력되는것을 확인할 수 있다. ALL 카테고리에 CSS가 부여되어, 현재 카테고리가 ALL 이고, 검색결과가 존재하므로 결과물이 출력되어야 할 것 같지만, 실제로는 이전에 선택한 카테고리인 IT 일반 이 유지되고, 해당 카테고리 결과는 존재하지 않으므로 다음과 같은 UI가 보이는것을 확인할 수 있다. 
<img width="709" alt="image" src="https://user-images.githubusercontent.com/36416495/210740984-47160078-8bca-4cdc-a5a5-0947bc020178.png">

4. 다시한번 이전의 검색어를 입력하면, 카테고리가 여전히 유지되고 있던게 맞음을 확인할 수 있다.5. 
<img width="766" alt="image" src="https://user-images.githubusercontent.com/36416495/210741133-0313cd35-d01d-4b15-abee-0c42b6374eb7.png">

**Comment by yenawee** [comment]
이곳은 친바입니다 🥰
