### ISSUE TITLE
집현전 실록 재생 버튼 관련 문의 사항

### ISSUE THREAD

**Issue by chanhihi** [Together42/frontend#88]
# 🤷‍♀️ 질문 대상
프론트엔드 여러분

# 👀 질문 내용
https://together42.github.io/frontend/2022-timeline
집현전 실록 재생하고나서 정지 시킬 수 있는 버튼이 없습니다.

# ⌛ 연락 가능 시간
Anytime

**Comment by keinn51** [comment]
@chanhihi 지금 봤네요 확인해볼게요 이슈 감사합니당~!!

**Comment by keinn51** [comment]
@yenawee 이렇습니다

**Comment by keinn51** [comment]
@chanhihi 
https://github.com/Together42/frontend/pull/106
해당 풀리퀘에서 재생 버튼을 아예 없애는 방식으로 해결 완료했습니다!
