### ISSUE TITLE
사서 달력 페이지에서 무한 선택 가능

### ISSUE THREAD

**Issue by jhj9109** [Together42/frontend#93]
# 버그 사항
(아직 미완성으로 보이지만) 사서 달력 페이지에서 어떠한 날짜도 모두 선택 가능 && 중복 선택 가능

# 버그 재현
- 사서 달력 페이지를 클릭한다.
- 캘린더를 마구 마구 클릭한다.
- 이미 선택(?)된 날에 클릭을 하면  UI적으로 여러 블록이 생성된다. 실제로는 하나의 블록만 살아남는다.
- 여러 날짜를 드래그하면 UI적으로 긴 블록이 생성된다. 실제로는 가장 왼쪽의 블록만 살아남는다.
- (추가 by jimin 제보) 이미 생성된 블록이 있는 날짜에 드래그앤드롭으로 추가하면 실제로 추가 된다. (백엔드쪽 로직이 이것을 딱 받아줄수있게 코딩되어있다)
<img width="746" alt="image" src="https://user-images.githubusercontent.com/36416495/218986792-ac4e9461-ed56-4e5d-806b-9260dbc803db.png">
<img width="747" alt="image" src="https://user-images.githubusercontent.com/36416495/219058080-18c45c82-7899-4e57-95d5-e99ed67d9f86.png">

**Comment by keinn51** [comment]
이 부분은 해결 되었습니다!
