### ISSUE TITLE
사서 로테이션 날짜 선택 개선 문의

### ISSUE THREAD

**Issue by oh2o** [Together42/frontend#99]
# 🤷‍♀️ 질문 대상

사서 로테이션 날짜 선택 기능

# 👀 질문 내용

평일에만 사서 업무를 하니까 주말은 클릭이 안되게 하면 좋을 것 같습니다. 개선이 가능할까요?

<img width="413" alt="Screenshot 2023-02-28 at 3 13 36 PM" src="https://user-images.githubusercontent.com/110885355/221769540-c07224fd-b8a2-4d52-af4a-d0ff43472d9b.png">

# ⌛ 연락 가능 시간

평일 오후 7시 이전

**Comment by jhj9109** [comment]
@oh2o 넵, 가능할것으로 예상합니다.

먼저  사서달력부분의 기능 업데이트에 우선순위를 두고 진행하느라 아직 로테이션 신청하는 부분은 업데이트 하지 못하였습니다.
UX적으로 어색한 부분도 있지만, (신청기간동안엔) 활용에는 큰 무리가 없다고 봐서 그렇게 결정했습니다.

사서 신청기간이 끝났는데, 신청이 가능한 부분등, 다소 급한 부분부터 한번 빠르게 버그 픽스 진행 후,
언급해 주신 부분들은 다음 사서 로테이션 신청기간 이전에 업데이트 하도록 하겠습니다~

**Comment by oh2o** [comment]
감사합니다~ 이슈는 close 하면 되나요?

**Comment by jhj9109** [comment]
그런식으로 닫을수도 있을것 같고, 아니면 언급하신 기능 업데이트 하면서 닫아도 됩니다

**Comment by keinn51** [comment]
@oh2o 이슈 감사드립니다!
